# Generated by Django 6.0.1 on 2026-02-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeprogram',
            name='max_credits_per_semester',
            field=models.PositiveIntegerField(default=24, help_text='Maximum credits a student can enroll in per semester'),
        ),
    ]
